name: Build and Release

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ghcr.io/jhofer-cloud/http-mirror-server
  UPDATER_IMAGE_NAME: ghcr.io/jhofer-cloud/http-mirror-updater

jobs:
  test:
    name: Test Go Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          cache: true

      - name: Run tests
        run: |
          go mod download
          go test -v ./...
          go vet ./...

      - name: Check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

  build:
    name: Build ${{ matrix.image }}
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        include:
          - image: server
            dockerfile: ./Dockerfile.server
            name: ghcr.io/jhofer-cloud/http-mirror-server
            title: HTTP Mirror Server
            description: Web server component for HTTP Mirror
          - image: updater
            dockerfile: ./Dockerfile.updater
            name: ghcr.io/jhofer-cloud/http-mirror-updater
            title: HTTP Mirror Updater
            description: Updater component for HTTP Mirror
    outputs:
      server-digest: ${{ matrix.image == 'server' && steps.build.outputs.digest || '' }}
      updater-digest: ${{ matrix.image == 'updater' && steps.build.outputs.digest || '' }}
      server-image: ${{ env.SERVER_IMAGE_NAME }}
      updater-image: ${{ env.UPDATER_IMAGE_NAME }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version (for releases)
        id: version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-,enable=${{ github.event_name != 'pull_request' }}
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
          labels: |
            org.opencontainers.image.title=${{ matrix.title }}
            org.opencontainers.image.description=${{ matrix.description }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=${{ matrix.image }}
            type=gha,scope=go-deps
          cache-to: |
            type=gha,mode=max,scope=${{ matrix.image }}
            type=gha,mode=max,scope=go-deps

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name != 'pull_request'
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run Trivy vulnerability scanner (Server)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.server-image }}@${{ needs.build.outputs.server-digest }}
          format: "sarif"
          output: "trivy-server-results.sarif"

      - name: Run Trivy vulnerability scanner (Updater)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.updater-image }}@${{ needs.build.outputs.updater-digest }}
          format: "sarif"
          output: "trivy-updater-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-server-results.sarif"
          category: "trivy-server"

      - name: Upload Trivy updater scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-updater-results.sarif"
          category: "trivy-updater"

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build, security-scan]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        run: |
          echo "## What's Changed" > CHANGELOG.md
          git log --oneline --no-decorate $(git describe --tags --abbrev=0 HEAD~1)..HEAD >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## Docker Images" >> CHANGELOG.md
          echo "- Server: \`${{ env.SERVER_IMAGE_NAME }}:${{ steps.version.outputs.version }}\`" >> CHANGELOG.md
          echo "- Updater: \`${{ env.UPDATER_IMAGE_NAME }}:${{ steps.version.outputs.version }}\`" >> CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/gh-action-create-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
